name: Generate Release Notes

on:
  push:
    tags:
      - 'v*.*.*' # Runs when you create a version tag like v1.0.0
  workflow_dispatch:

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate release notes
        run: |
          echo "### 🚀 Release Notes for $(git describe --tags)" > release_notes.md
          git log -1 --pretty=format:"%h - %s (%an)" >> release_notes.md
          cat release_notes.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release_notes.md
