name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Project to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build || echo "No build script found, skipping build step"

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}        # Your Vercel Token
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}      # Your Org/User ID
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # Your Project ID
          working-directory: ./
          vercel-args: '--prod'
